name: nexa

services:
  mysql:
    image: mysql
    container_name: nexa-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nexa
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - nexa_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis
    container_name: nexa-redis
    ports:
      - "6379:6379"
    volumes:
      - nexa_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  nexa_mysql_data:
  nexa_redis_data:
